select concat(substr(`e_nl`,1,6),'-',substr(`e_nl`,7)) AS `nolesen`,
`e_np` AS `company`,
`e_ap1` AS `address`,
`e_ap2` AS `address2`,
`e_ap3` AS `address3`,
`e_as1` AS `address_surat`,
`e_as2` AS `address_surat2`,
`e_as3` AS `address_surat3`,
`e_notel` AS `phone`,
`e_nofax` AS `fax`,
`e_email` AS `email`,
`e_npg` AS `pegawai`,
`e_jpg` AS `jawatan`,
`e_apnegeri` AS `state_id`,
`e_apdaerah` AS `daerah_id`,
'08' AS `category_id`,
'16' AS `subcategory_id`,
'on' AS `status` from `kilang` where `e_kat` = 'PL104';
