select `List_Peniaga`.`No_Lesen` AS `nolesen`,
`List_Peniaga`.`Nama_Pemegang_Lesen` AS `company`,
`List_Peniaga`.`Alamat_Premis_1` AS `address`,
`List_Peniaga`.`Alamat_Premis_2` AS `address2`,
`List_Peniaga`.`Alamat_Premis_3` AS `address3`,
`List_Peniaga`.`Negeri_Permit_Berlesen` AS `negeri`,
`List_Peniaga`.`Daerah_Permit_Berlesen` AS `daerah`,
`List_Peniaga`.`Alamat_Surat_Menyurat_1` AS `address_surat`,
`List_Peniaga`.`Alamat_Surat_Menyurat_2` AS `address_surat2`,
`List_Peniaga`.`Alamat_Surat_Menyurat_3` AS `address_surat3`,
'03' AS `category_id`,
`List_Peniaga`.`Sub_Kategori` AS `subcategory_id`,
`List_Peniaga`.`Active` AS `status` from (`List_Peniaga` join `Data_Pelesen` on((`List_Peniaga`.`No_Lesen` = `Data_Pelesen`.`No_Lesen`))) where ((`List_Peniaga`.`Forms` = 'F3') or (`List_Peniaga`.`SubForm` = 'F3') or (`List_Peniaga`.`SubForm2` = 'F3'));
